---
toc: false
---

# Introduction

The suppression of native vegetation in the Amazon and Cerrado biomes is a matter of great concern due to its potential impact on the environment and human well-being.
Understanding the drivers and effects of this phenomenon is crucial to guide policies to avoid further natural vegetation suppression and mitigate negative impacts.
However, this is a challenging task since the factors involved in this phenomenon are diverse, heterogeneous, and can even be contradictory.
Existing literature suggests that native vegetation suppression is caused by economic fluctuations [@hargrave-2012], conservation policies [@pfaff-2015], population distribution [@jusys-2016], land tenure [@cattaneo-2001], livestock and crop productions [@bowman-2016].
On the other side, vegetation removal may impact human health [@santos-2018], climate regime [@silva-2023], regional hydrology [@cavalcante-2019], soil properties [@dias-2022] and biodiversity [@gestich-2021].

Unfortunately, much of the research in this area tends to focus on only a few dimensions of the problem, rather than taking a holistic approach.
This narrow focus often fails to capture the full extent of the issue and can lead to oversimplifications or misdirection in efforts to solve it.

This project aims to predict and understand the causes and impacts of native vegetation suppression in the Cerrado and Amazon biomes, considering environmental and anthropic dimensions.
The results will provide a deeper understanding of the relationships between land use changes, environmental factors, and social dynamics related to native vegetation suppression.

Regression and classification models will be applied to existing data on land use changes, environmental factors, and social variables in the Cerrado and Amazon biomes.
The models will be used to identify patterns and relationships between these variables.

The results of this project will contribute to a better understanding of the causes and impacts of native vegetation suppression in the Cerrado and Amazon biomes.
This knowledge will inform the development of effective conservation and management strategies that will help to protect these vital and unique ecosystems.

::: {.callout-important collapse="true"}
READ: land use theory

-   https://doi.org/10.1016/j.futures.2014.11.005
-   https://doi.org/10.1080/1747423X.2020.1811792
:::

# Objectives

The main objective of this project is to develop a framework to model deforestation and its impacts, using variables of different dimensions (environment and society) to predict quantitative estimations of deforestation and its social and environmental impacts. The main objective will be composed of related questions:

(1) What are the qualitative and quantitative variables that are associated with deforestation and its impacts?

(2) What are the possibilities and challenges to translate these variables in a common format to provide information to the models?

(3) What are the importance of the variables, and how do they interact between one another, according to the models?

(4) What inferences can be made about the model results and policies being applied to curb deforestation?

# References {.unnumbered}
