---
title: Visão Geral
---

# Introdução {#sec-introduction}

A Supressão da Vegetação Nativa ({{< glossary "supressão de vegetação natural" display="SVN" >}}) é motivo de grande preocupação devido ao seu impacto sobre o meio ambiente e o bem-estar humano. Existe um interesse internacional na proteção de formações de vegetação natural, a fim de evitar efeitos negativos como emissões de gases de efeito estufa e a perda de biodiversidade. A compreensão das causas e das consequências deste fenômeno é crucial para orientar políticas destinadas a evitar uma maior SVN e a atenuar seus impactos negativos. No entanto, esta é uma tarefa difícil, uma vez que os fatores envolvidos neste fenômeno são diversos, heterogêneos e podem até ser contraditórios. Alguns dos fatores que já foram apontados como causas da SVN são: flutuações econômicas [@hargrave-2012], políticas de conservação [@pfaff-2015], distribuição da população [@jusys-2016], posse da terra [@cattaneo-2001] e produção pecuária e agrícola [@bowman-2016]. Por outro lado, já foi apontado que a SVN pode ter impacto na saúde humana [@santos-2018], no regime climático [@silva-2023], na hidrologia regional [@cavalcante-2019], nas propriedades do solo [@dias-2022] e na biodiversidade [@gestich-2021].

Quando observamos esses fatores citados, percebemos a complexidade de processos que ocorrem em conjunto da {{< glossary "supressão de vegetação natural" display="SVN" >}}, sendo que esses processos podem ser analisados sob a perspectiva de diferentes disciplinas, como a Antropologia, Sociologia, Geografia, Economia, e Ecologia. Portanto, a adoção de uma abordagem interdisciplinar é essencial para a descrição da SVN de uma maneira ampla, que tenha a capacidade de descrever esse fenômeno através de perspectivas diversas [@turner-2020]. Porém, desenvolver pesquisas interdisciplinares é um desafio, sendo que não há consenso sobre a própria concepção do que se define como interdisciplinar [@zscheischler-2015]. Uma das possibilidades de se atingir esse patamar é de adotar um paradigma filosófico semelhante entre diferentes disciplinas [@danermark-2002], facilitando o diálogo entre conhecimentos gerados por diferentes métodos.

A partir da problemática exposta acima, o presente trabalho tem como **objetivo central**, desenvolver e aplicar um Modelo Teórico Geral da {{< glossary "supressão de vegetação natural" display="SVN" >}}, que seja capaz de ser utilizado em análises por diferentes disciplinas. O desenvolvimento do modelo teórico é feito a partir de um paradigma filosófico conhecido como Realismo Crítico, que define a perspectiva ontológica e epistemológica adotada na pesquisa. A aplicação do modelo teórico é feita a partir do emprego da Teoria Geral dos Campos de Bourdieu, como uma perspectiva da Sociologia, e de modelos estatísticos espaciais, como uma perspectiva da Geografia. O contexto temporal e espacial da aplicação do modelo teórico se dá no passado recente dos biomas Amazônia e Cerrado.

A **hipótese central** é de que é possível e frutífero utilizar um modelo teórico para descrever o processo da {{< glossary "supressão de vegetação natural" display="SVN" >}} em um recorte espacial e temporal específico, através de métodos de diferentes disciplinas. 

O método proposto é inovador no sentido de empregar um modelo teórico como uma base comum, para a condução e interpretação dos resultados das análises estatística e sociológica, apresentando uma nova maneira de conduzir pesquisas interdisciplinares no tema da {{< glossary "supressão de vegetação natural" display="SVN" >}}. A contribuição do modelo teórico é de fornecer uma descrição detalhada do mecanismo causal da SVN, e de sua manifestação empírica. A partir disso, é fornecida uma ferramenta de interpretação para os resultados das análises estatística e sociológica, em que os resultados dessas anáises são confrontados pela descrição fornecida pelo modelo teórico.

# Método Geral

# Referências {.unnumbered}
