project:
  type: book
  output-dir: _book

book:
  title: "Dimensions of deforestation causes in the Amazon and Cerrado"
  author:
  - name: Hugo Tameirão Seixas
    email: seixas.hugo@protonmail.com
    url: hugotseixas.com
    affiliations:
      - name: State University of Campinas
  date: "3/21/2023"
  license: CC BY-NC-ND 4.0
  favicon: /figs/art/logo.png
  sidebar:
    search: true
    logo: /figs/art/logo.png
  comments:
    giscus:
      repo: hugotseixas/tica-book
      category: "Announcements"
      category-id: "DIC_kwDOJMlNNs4CVCYq"
      reactions-enabled: false
  chapters:
    - index.qmd
    - 00_glossary.qmd
    - 01_introduction.qmd
    - 02_methods.qmd
    - 03_results.qmd
    - 04_discussion.qmd
    - 05_conclusions.qmd
  appendices:
    - 10_research_paradigm.qmd

bibliography: references.bib

format:
  html:
    theme: lux
    toc: true
    toc-depth: 3
    toc-title: Content
    reference-location: margin
    mermaid:
      theme: neutral

execute:
  freeze: auto
