project:
  type: book
  output-dir: _book

lang: pt

book:
  title: "Explorando dimensões da Supressão de Vegetação Natural através de uma teoria geral"
  author:
  - name: Hugo Tameirão Seixas
    email: seixas.hugo@protonmail.com
    url: hugotseixas.com
    affiliations:
      - name: Universidade Estadual de Campinas
  date: "4/23/2024"
  license: CC BY-NC-ND 4.0
  favicon: /figs/art/logo.png
  sidebar:
    style: "docked"
    search: true
    logo: /figs/art/logo.png
  comments:
    hypothesis:
      theme: clean
  chapters:
    - index.qmd
    - 00_glossary.qmd
    - 10_research_paradigm.qmd
    - 01_introduction.qmd
    - 02_methods.qmd
    - 03_results.qmd
  appendices:
    - 11_research_data.qmd

glossary:
  path: glossary.yml
  popup: hover
  show: true

bibliography: 
  - references.bib
  - references_packages.bib

format:
  html:
    theme: lux
    toc: true
    toc-depth: 4
    toc-title: Content
    reference-location: margin
    mermaid:
      theme: neutral
